# Generated by Django 5.0.6 on 2024-06-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='wine_images/')),
                ('nome', models.CharField(max_length=255)),
                ('vinicula', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('uva', models.CharField(max_length=100)),
                ('safra', models.CharField(max_length=4)),
                ('tamanho', models.CharField(choices=[('meia', 'Meia Garrafa'), ('inteira', 'Garrafa Inteira')], max_length=10)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('fornecedores', models.ManyToManyField(related_name='vinhos', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('vinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine')),
            ],
        ),
    ]
